sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: AX8A87VH+PwpBVBoYr3x785bio9OSvAIdnjtn8fN1ZJ+ng1Lz2234K7xcuc9+KRJXNafIliDxVWeVbDLMwln1jlReaBXrq/oKa2ami5RMIgshPhLoEjpb7PpLB3iQ1IK0S5zo92zgcEpD1pqLkcgzqDsBQMh3pDaX9Z1NsBRLxfPJy9hWxvVsmIThj53G78mKZtw44l0pUMlKan1iZfMSt63qOxaHdEBAy2q/Cd4V83Uzxv66fIn/UTj6I+awmFaib48Ce3EjhI9xtWeCNBApjqaqdZCpP+Sd1ujYu7MtPo8TcENZrTya6TUBxMadb6rEJ0bA/Wg3Ors4KNrW+xE6kG/2f8bs13TEdaQDnY88oProOvnJEwYO75u/2o4a43RvRRJhOksMfINUb8y7a//o7i3IkvBNh1rxEeB0JyYCRv1XZ8c/8DrTX7vtefSfUe1KZ8Yy2/kAMw8u14kpGPQEEZEeKLd1elrCkrk9IGeZV46FnLI90uGCWJsyiy0FCLheCMzLt1AwNtywkye+4ZrOwVYkT9TDIcOdMk6Maapm1gJM5Nka9v59xbWKErG5TIIQv5Z2jh5Guct4aVOY0KCpTjHmugtkvBO06WDQUwU5vHIQzi9Ux6i4vwzZKk3F5GtO71KmU7FvJ+CdG97aEqJhnBpegFS07uV7VZOGmcQ25s=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Ink-Stain--Tache-d-encre----Complete_3975
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy